name: test

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/Unit/ControllersTest
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/Unit/ServiceTest

steps:
  - uses: actions/checkout@v2
  - uses: php-actions/composer@v5 # or alternative dependency management
  - name: run tests
    run: composer test
  - name: change owner of phpcs
    run: sudo chmod 777 ./vendor/bin/phpcs
  - name: sniff
    run: composer sniff
