name: test

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/Unit/ControllersTest
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/Unit/ServiceTest

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      # we may use whatever way to install phpcs, just specify the path on the next step
      # however, curl seems to be the fastest
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: run codesniffs
        run: php phpcs.phar --standard=phpcs.xml
